name: Run all tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.0
          - 3.1
          - 3.2

    name: Run gem tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
